<?php
// $Id$

/**
 * @file ding_panels_layouts.module
 * Provides a few library-related Panels layouts.
 */

/**
 * Implementation of hook_panels_layouts()
 */
function ding_panels_layouts_panels_layouts() {
  $items = array();
  $items['threecol_left_stacked'] = array(
    'title' => t('Three column left stacked'),
    'icon' => 'threecol_left_stacked.png',
    'theme' => 'panels_threecol_left_stacked',
    'css' => 'threecol_left_stacked.css',
    'panels' => array(
      'top' => t('Top'),
      'left' => t('Left side'),
      'middle' => t('Middle column'),
      'right' => t('Right side'),
      'bottom' => t('Bottom'),
    ),
  );
  $items['twocol_left_stacked'] = array(
    'title' => t('Two column left stacked'),
    'icon' => 'twocol_left_stacked.png',
    'theme' => 'panels_twocol_left_stacked',
    'css' => 'twocol_left_stacked.css',
    'panels' => array(
      'top' => t('Top'),
      'left' => t('Left side'),
      'right' => t('Right side'),
      'bottom' => t('Bottom'),
    ),
  );
  return $items;
}

