<?php
// $Id$

/**
 * @file ding_library_map.module
 * Displays library nodes on a map with additional information shown on mouse over
 */

function ding_library_map_block($op = 'list', $delta = 0, $edit = array())
{
  $func = __FUNCTION__.'_'.$op;
  return $func($delta, $edit);
}

function ding_library_map_block_list($delta = 0, $edit = array())
{
  $block[0]["info"] = t('Library map');
  return $block;
}

function ding_library_map_block_view($delta = 0, $edit = array())
{
  $nodes = db_query("SELECT location_instance.nid AS nid,
             location.latitude AS location_latitude,
             location.longitude AS location_longitude,
             location.latitude AS gmap_lat,
             location.longitude AS gmap_lon
           FROM location location 
           LEFT JOIN location_instance location_instance ON location.lid = location_instance.lid
           LEFT JOIN node node ON location_instance.vid = node.vid
           WHERE (node.status <> 0) AND (node.type in ('library'))");
  
	$libraries = array();
	while ($node = db_fetch_object($nodes))
	{
		$libraries[] = node_load($node->nid);
	}

  $block = array();
  $block['subject'] = 'Library map';
  $block['content'] = theme('ding_library_map', $libraries);
  return $block;
}

function ding_library_map_theme($existing, $type, $theme, $path)
{  
  return array(
    'ding_library_map' => array(
      'arguments' => array('nodes' => NULL),
      'template' => 'ding_library_map'
    ),
  );
}


