<?php
// $Id$

/**
 * @file ding_library_map.module
 * Displays library nodes on a map with additional information shown on mouse over
 */

/**
 * Implementation of hook_block.
 */
function ding_library_map_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks = array();
      $blocks[0] = array(
        'info' => t('Ding library map'),
        'cache' => BLOCK_CACHE_GLOBAL,
      );
      return $blocks;
    case 'view':
      return ding_library_map_block_view($delta);
  }
}

/**
 * Render the block output.
 *
 * @param integer $delta
 *    The block delta.
 * @return array
 *    Rendered block with subject and content.
 */
function ding_library_map_block_view($delta = 0) {
  $nodes = db_query("SELECT location_instance.nid AS nid,
             location.latitude AS location_latitude,
             location.longitude AS location_longitude,
             location.latitude AS gmap_lat,
             location.longitude AS gmap_lon
           FROM location location 
           LEFT JOIN location_instance location_instance ON location.lid = location_instance.lid
           LEFT JOIN node node ON location_instance.vid = node.vid
           WHERE (node.status <> 0) AND (node.type in ('library'))");
  
	$libraries = array();
	while ($node = db_fetch_object($nodes))
	{
		$libraries[] = node_load($node->nid);
	}

  $block = array();
  $block['subject'] = 'Library map';
  $block['content'] = theme('ding_library_map', $libraries);
  return $block;
}

/**
 * Implementation of hook_theme().
 */
function ding_library_map_theme($existing, $type, $theme, $path) {  
  return array(
    'ding_library_map' => array(
      'arguments' => array('nodes' => NULL),
      'template' => 'ding_library_map'
    ),
  );
}


