<?php
// $Id$

/**
 * @file ding_panels_content.module
 * Provides a few library-related panes for the Panels module.
 */

/**
 * Implementation of hook_theme().
 */
function ding_panels_content_theme($existing, $type, $theme, $path) {
  return array(
    'ding_panels_content_library_title' => array(
      'arguments' => array('node' => NULL),
      'file' => 'ding_panels_content.theme.inc',
      'template' => 'ding_panels_content_libary_title',
      'preprocess functions' => array('ding_panels_content_preprocess_library_title'),
    ),
    'ding_panels_content_library_location' => array(
      'arguments' => array('node' => NULL),
      'file' => 'ding_panels_content.theme.inc',
      'template' => 'ding_panels_content_libary_location',
      'preprocess functions' => array('ding_panels_content_preprocess_library_location'),
    ),
  );
}

/**
 * Implementation of hook_panels_content_types().
 */
function ding_panels_content_panels_content_types() {
  $items = array();
  $items['ding_panels_content'] = array(
    'title' => t('Library page'),
    'content_types' => '_ding_panels_content_types',
    'render callback' => '_ding_panels_content_render',
    'title callback' => '_ding_panels_content_title',
  );
  return $items;
}

/**
 * Return all content types available.
 */
function _ding_panels_content_types() {
  return array(
    'library_title' => array(
      'title' => t('Library title and navigation'),
      'description' => t('The title and navigation for a library page.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
    'library_location' => array(
      'title' => t('Library location'),
      'description' => t('Shows the address, map and other locative information for the library.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
    'library_hours' => array(
      'title' => t('Library opening hours'),
      'description' => t('Shows the library opening hours.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
    'library_about' => array(
      'title' => t('Library about text'),
      'description' => t('Shows the main library description text in its full length.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
    'library_feature_list' => array(
      'title' => t('Library feature list'),
      'description' => t('Simple list of library features, containing only the title.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
    'library_feature_detail_list' => array(
      'title' => t('Library detailed feature list'),
      'description' => t('More detailed view of library features with pictures and description.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
  );
}

/**
 * Return the pane contents.
 */
function _ding_panels_content_render($subtype, $conf, $panel_args, $context) {
  $block = new stdClass();
  $node = $context->data;
  switch($subtype) {
    case 'library_title':
      $block->content = theme('ding_panels_content_library_title', $node);
      break;
    case 'library_location':
      $block->content = theme('ding_panels_content_library_location', $node);
      break;
    case 'library_hours':
      $block->title = t('Opening hours');
      // Ask CCK to render the opening hours field for us.
      $block->content = content_format('field_opening_hours', $node->field_opening_hours, 'default', $node);
      break;
    case 'library_about':
      // Render the node body as block content.
      $block->content = check_markup($node->body, $node->format, $node->language);
      break;
    case 'library_feature_list':
    case 'library_feature_detail_list':
      $block->title = t('Services and facilities');
      $block->content = theme_item_list(_ding_panels_content_features_by_library($node));
  }
  return $block;
}

/**
 * Return the pane titles.
 */
function _ding_panels_content_title($subtype, $conf, $context) {
  switch($subtype) {
    case 'library_title':
      return t('Library title and navigation');
    case 'library_location':
      return t('Library location');
    case 'library_hours':
      return t('Library opening hours');
    case 'library_about':
      return t('Library about text');
    case 'library_feature_list':
    case 'library_feature_detail_list':
      return t('Services and facilities');
  }
}

/**
 * Find all features related to a library node.
 *
 * @param object $node
 *    The library node we want features for.
 * @return array
 *    Array of feature titles, keyed by node id.
 */
function _ding_panels_content_features_by_library($node) {
  // First, get the feature with a nice bit of SQL.
  $query = db_query("
    SELECT n.nid, n.title
    FROM content_field_feature_ref AS fr
    LEFT JOIN node AS n ON ( n.nid = fr.field_feature_ref_nid )
    WHERE fr.field_feature_ref_nid IS NOT NULL
    AND fr.nid = %d
    ORDER BY fr.delta ASC;
  ", $node->nid);

  // And stick them in a nice little array.
  $features = array();
  while ($row = db_fetch_array($query)) {
    $features[$row['nid']] = $row['title'];
  }
  return $features;
}

