<?php // $Id$

/**
 * @file ding_panels.module
 * Panels plugins for the Ding project.
 */

/**
 * Implementation of hook_theme().
 */
function ding_panels_theme($existing, $type, $theme, $path) {
  return array(
    'ding_panels_content_library_title' => array(
      'arguments' => array('node' => NULL),
      'file' => 'ding_panels.theme.inc',
      'template' => 'ding_panels_content_libary_title',
      'preprocess functions' => array('ding_panels_content_preprocess_library_title'),
    ),
    'ding_panels_content_library_location' => array(
      'arguments' => array('node' => NULL),
      'file' => 'ding_panels.theme.inc',
      'template' => 'ding_panels_content_libary_location',
      'preprocess functions' => array('ding_panels_content_preprocess_library_location'),
    ),
    'ding_panels_library_portal_title' => array(
      'arguments' => array('node' => NULL),
      'file' => 'ding_panels.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function ding_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

