<?php
// $Id$

/**
 * @file ding_panes.module
 * Provides a few library-related panes for the Panels module.
 */

/**
 * Implementation of hook_theme().
 */
function ding_panes_theme($existing, $type, $theme, $path) {
  return array(
    'ding_panes_title' => array(
      'arguments' => array('node' => NULL),
      'file' => 'ding_panes.theme.inc',
      'template' => 'ding_panes_title',
      'preprocess functions' => array('ding_panes_preprocess_title'),
    ),
  );
}

/**
 * Implementation of hook_panels_content_types().
 */
function ding_panes_panels_content_types() {
  $items = array();
  $items['LIBRARY_PAGE'] = array(
    'title' => t('Library page'),
    'content_types' => '_ding_panes_types',
    'render callback' => '_ding_panes_render',
    'title callback' => '_ding_panes_title',
  );
  return $items;
}

/**
 * Return all content types available.
 */
function _ding_panes_types() {
  return array(
    'library_title' => array(
      'title' => t('Library title and navigation'),
      'description' => t('The title and navigation for a library page.'),
      'required context' => new ctools_context_required(t('Node'), 'node'),
      'category' => array(t('Library page'), -9),
    ),
  );
}

/**
 * Return the pane contents.
 */
function _ding_panes_render($subtype, $conf, $panel_args, $context) {
  $block = new stdClass();
  switch($subtype) {
    case 'library_title':
      $block->content = theme('ding_panes_title', $context->data);
      break;
  }
  return $block;
}

/**
 * Return the pane titles.
 */
function _ding_panes_title($subtype, $conf, $context) {
  return 'Library title and navigation';
}

